services:
  baogpt:
    image: bao/rag-gpt-0.1:latest
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
      dockerfile: ./docker/Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ./data/:/home/${UID}/app/data
    ports:
      - 8000:8000
    environment:
      PORT: 8000
